
#include "include/globals.h"

extern bool boostSensor;
extern bool debugEnabled;
extern bool boostLimit;
extern bool fullAuto;
extern bool fuelPumpControl;
extern bool radioEnabled;
extern bool stickCtrl;
extern bool horn;
extern bool manual;
extern bool truePower;
extern bool tccLock;
extern bool stick;
extern bool autoGear;
extern bool adaptive;
extern bool evalGear;
extern bool tpsSensor;
extern bool boostSensor;
extern bool debugEnabled;
extern bool boostLimit;
extern bool diffSpeed;
extern bool rpmSpeed;
extern bool batteryMonitor;
extern bool exhaustPresSensor;
extern bool datalogger;
extern bool w124speedo;
extern bool w124rpm;
extern bool exhaustTempSensor;
extern bool boostLimit;
extern bool boostLimitShift;
extern bool resistiveStick;
extern struct ConfigParam config;
void initConfig();
void pollConfigMode();
void getFeatures();
void getGears();
void setFeatures(int asset, int value);
void getConfig();
void setConfig(int asset, int value);
void setUpGear(int asset, int value);
void setDownGear(int asset, int value);
void setConfigFloat(int asset, float fvalue);
void serialConfig();
void serialWatch();
